name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    name: Test
    strategy:
      matrix:
        pyver: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os: [ubuntu, macos, windows]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.pyver }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyver }}
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"    # - name: Cache
    - name: Cache PyPI
      uses: actions/cache@v2
      with:
        key: pip-ci-${{ runner.os }}-${{ matrix.pyver }}-${{ hashFiles('requirements.dev.txt') }}
        path: ${{ steps.pip-cache.outputs.dir }}
        restore-keys: |
            pip-ci-${{ runner.os }}-${{ matrix.pyver }}
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: requirements.dev.txt
    - name: Install itself
      run: |
        pip install -e .
    - name: Run unittests
      env:
        COLOR: 'yes'
      run: |
        pytest -v
